from decimal import *

PLOT_PRECISION = 0.01
PLOT_SCALING_LIMITS_FACTOR = 1.125

#WINDOW
SCREEN_HEIGHT = 1080
SCREEN_WIDTH = 1920
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 800
PLOTWINDOW_PROP = 8/9
PLOTWINDOW_HEIGHT = WINDOW_HEIGHT*PLOTWINDOW_PROP
PLOTWINDOW_WIDTH = WINDOW_WIDTH

#PLOTWINDOW
INITIAL_XY_LIMITS = 3
PLOT_SCALING_LIMITS_UNIT_FACTOR = 1.25