
DEFAULT_PLOT_PRECISION = 0.01
PLOT_SCALING_LIMITS_FACTOR = 1.125

#WINDOW
SCREEN_HEIGHT = 1080
SCREEN_WIDTH = 1920
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 800
PLOTWINDOW_PROP = 8/9
PLOTWINDOW_HEIGHT = WINDOW_HEIGHT*PLOTWINDOW_PROP
PLOTWINDOW_WIDTH = WINDOW_WIDTH

#PLOTWINDOW
INITIAL_XY_LIMITS = 3
PLOT_SCALING_LIMITS_UNIT_FACTOR = 1.25

#STYLE
MAIN_WINDOW_BACKGROUND_COLOR = "#2a2a2a"
PLOT_WINDOW_BACKGROUND_COLOR = "#ededed"
PLOTWINDOW_TEXT_SIZE = 9

STATUSBAR_BACKGROUND_COLOR = "#292929"
STATUSBAR_BORDER_COLOR = "#2f2f2f"
STATUSBAR_TEXT_COLOR = "#ebebeb"
STATUSBAR_ERROR_TEXT_COLOR = "#e9313a"
STATUSBAR_MESSAGE_TIME = 3

LABEL_TEXT_COLOR = "#cacaca"

LINE_COLOR = "#4a4a4a"
LINE_TEXT_COLOR = "#ebebeb"
LINE_PADDING = "3px"

PLOT_BUTTON_BACKGROUND_COLOR = "#4375a3"
PLOT_BUTTON_TEXT_COLOR = "#ebebeb"
IMPORTANT_BUTTON_BACKGROUND_COLOR = "#436280"
BUTTON_TEXT_COLOR = "#ebebeb"
